# Generated by Django 4.2.1 on 2023-06-28 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
    ]
